version: "3"

networks:
  ethernet:
    external: true

services:
  gl-mail-manager-golang:
    container_name: gl-mail-manager-golang
    image: gl-mail-manager-golang
    links:
      - gl-mail-manager-rabbitmq
    volumes:
      - .:/go/src/github.com/Sharykhin/gl-mail-manager
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile
    env_file:
      - .docker/golang/.env
    depends_on:
      - gl-mail-manager-rabbitmq
    networks:
      - ethernet

  gl-mail-manager-rabbitmq:
    container_name: gl-mail-manager-rabbitmq
    image: gl-mail-manager-rabbitmq
    build:
      context: .
      dockerfile: .docker/rabbitmq/Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .docker/rabbitmq/.env
    networks:
      - ethernet
